// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnmNZq4tLpVc8_jB9S3bnzPmffiPd7uVQ',
    appId: '1:998447083751:web:31be563c2043532b90f242',
    messagingSenderId: '998447083751',
    projectId: 'minoxiplan',
    authDomain: 'minoxiplan.firebaseapp.com',
    storageBucket: 'minoxiplan.firebasestorage.app',
    measurementId: 'G-SL35SWYCDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA-4Y8s3fUYV04ds8mwcE5ehZwd-izPVk',
    appId: '1:998447083751:android:1c724b88620c307a90f242',
    messagingSenderId: '998447083751',
    projectId: 'minoxiplan',
    storageBucket: 'minoxiplan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDN32vCDqTVoyQ37TjQ8HJTNY61EfyQ5w',
    appId: '1:998447083751:ios:6e43bed9e97b99df90f242',
    messagingSenderId: '998447083751',
    projectId: 'minoxiplan',
    storageBucket: 'minoxiplan.firebasestorage.app',
    iosBundleId: 'com.example.minoxPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDN32vCDqTVoyQ37TjQ8HJTNY61EfyQ5w',
    appId: '1:998447083751:ios:6e43bed9e97b99df90f242',
    messagingSenderId: '998447083751',
    projectId: 'minoxiplan',
    storageBucket: 'minoxiplan.firebasestorage.app',
    iosBundleId: 'com.example.minoxPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnmNZq4tLpVc8_jB9S3bnzPmffiPd7uVQ',
    appId: '1:998447083751:web:5877f1115e3af33490f242',
    messagingSenderId: '998447083751',
    projectId: 'minoxiplan',
    authDomain: 'minoxiplan.firebaseapp.com',
    storageBucket: 'minoxiplan.firebasestorage.app',
    measurementId: 'G-3WWJTDHB1N',
  );
}
